return {
	-- "nobbmaestro/nvim-andromeda",
	-- dependencies = {
	-- 	"tjdevries/colorbuddy.nvim",
	-- },
	-- config = function()
	-- 	require("andromeda").setup({
	-- 		preset = "andromeda",
	-- 		styles = {
	-- 			italic = true,
	-- 		},
	-- 		colors = {
	-- 			background = "#22232b",
	-- 			cyan = "#00ddbc", -- defaults to cyan
	-- 			pink = "#e9c6cc", -- defaults to pink
	-- 			purple = "#cbc3e6", -- defaults to pink
	-- 			yellow = "#f0d966",
	-- 			green = "#0de7c5",
	-- 			mono_1 = "#2f323c", -- secondary background and/or highlighting
	-- 			mono_2 = "#3a3e4b", -- used for highlighting
	-- 			mono_3 = "#464959", -- used for highlighting
	-- 			mono_4 = "#606064",
	-- 			mono_5 = "#a0a1a7", -- comments
	-- 			mono_6 = "#d5ced9", -- normal text
	-- 		},
	-- 	})
	-- 	local andromeda_lualine = require("andromeda.plugins.lualine")
	--
	-- 	require("lualine").setup({
	-- 		options = {
	-- 			theme = andromeda_lualine.theme,
	-- 		},
	-- 		sections = andromeda_lualine.sections,
	-- 		inactive_sections = andromeda_lualine.inactive_sections,
	-- 	})
	-- end,
}
