import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]

[env]
LANG = "en_US.UTF-8"
TERM = "xterm-256color"

[font]
size = 15.0
offset = { x = 0, y = 1 }

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
dynamic_padding = true
decorations = "Full"
opacity = 1.0
startup_mode = "Maximized"
